version: "2"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuserdbuser
    ports: 
      - "3306:3306"